using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

public class ItemList : MonoBehaviour
{
    public static ItemList instance;

    public delegate void EquipItemHandler(EquipItem item);
    public event EquipItemHandler OnEquipItemSelect;

    [SerializeField] private HeroButtonObject.ChangedImage changedImage;

    [Header("Toggles")]
    [SerializeField] private Toggle toggleConsume;
    [SerializeField] private Toggle toggleEquip;
    [SerializeField] private Sprite selectedImage;
    [SerializeField] private Sprite unselectedImage;

    [Header("List")]
    [SerializeField] private Button itemButtonPrefab;
    [SerializeField] private Transform itemListPanel;

    [Header("Inventory")]
    [SerializeField] private DungeonInventory dungeonInventory;
    [Header("Panel")]
    [SerializeField] private GameObject itemList;
    [SerializeField] private GameObject partyPanel;
    [SerializeField] private PartySelector partySelector;

    private Button currentSelect;

    private List<Button> equipItemButtons = new();
    private List<EquipItem> equipItemDatas = new();

    void Awake()
    {
        if (instance == null)
        {
            instance = this;
        }
        else if (instance != this)
        {
            Destroy(this.gameObject);
        }
    }
    void Start()
    {
        toggleConsume.onValueChanged.AddListener(OnToggleChanged);
        toggleEquip.onValueChanged.AddListener(OnToggleChanged);

        toggleConsume.isOn = true;
        RefreshItemList();
    }

    void OnEnable()
    {
        var clickHandler = FindObjectOfType<UIClickResetHandler>();
        if (clickHandler != null)
            clickHandler.RegisterResetCallback(ResetItemButton);
    }

    void OnToggleChanged(bool _)
    {
        RefreshItemList();
    }

    void PrintConsumeItem()
    {
        foreach (Transform child in itemListPanel)
        {
            Destroy(child.gameObject);
        }

        var items = PlayerItemManager.instance.GetOwnedConsumeItems();

        foreach (var ownedItem in items)
        {
            if (ownedItem.count <= 0) continue;
            Button itemButton = Instantiate(itemButtonPrefab, itemListPanel);
            TMP_Text itemName = itemButton.transform.Find("ItemName").GetComponent<TMP_Text>();
            TMP_Text itemAmount = itemButton.transform.Find("ItemAmount").GetComponent<TMP_Text>();

            itemName.text = ownedItem.itemData.name_item;
            itemAmount.text = "ÏàòÎüâ: " + ownedItem.count.ToString();

            // üî• ÌÅ¥Î°úÏ†Ä Î¨∏Ï†ú Î∞©ÏßÄ: Î°úÏª¨ Î≥ÄÏàòÎ°ú Î≥µÏÇ¨
            var currentItem = ownedItem.itemData;

            itemButton.onClick.AddListener(() =>
            {
                if (PlayerItemManager.instance.GetConsumeItemCount(currentItem) > 0)
                {
                    bool success = dungeonInventory.AddItem(currentItem);
                    if (success)
                    {
                        PlayerItemManager.instance.AddConsumeItem(currentItem, -1);
                        // üî• Ïù¥ UIManagerÍ∞Ä Ïó¥Î†§ ÏûàÎäî ÏÉÅÌÉúÏùº ÎïåÎßå Í∞±Ïã†
                        if (InventoryUIManager.instance.gameObject.activeInHierarchy)
                            InventoryUIManager.instance.RefreshUI();
                        RefreshItemList();
                    }
                }
            });
        }
    }

    void PrintEquipItems()
    {
        var items = PlayerItemManager.instance.ownedEquipItem;

        foreach (var ownedItem in items)
        {
            Button button = Instantiate(itemButtonPrefab, itemListPanel);
            Image buttonImage = button.GetComponent<Image>();
            TMP_Text itemName = button.transform.Find("ItemName").GetComponent<TMP_Text>();
            TMP_Text itemCount = button.transform.Find("ItemAmount").GetComponent<TMP_Text>();

            itemName.text = ownedItem.itemData.name_item;
            itemCount.text = ownedItem.count.ToString();

            Button capturedButton = button; //ÏòÅÏõÖ Î≤ÑÌäº
            Image capturedImage = buttonImage;

            // Ïû•ÎπÑÎäî Í∞úÎ≥Ñ Ïû•Ï∞© ÎòêÎäî Ï≤òÎ¶¨ Î∞©ÏãùÏóê ÎßûÏ∂∞ Î°úÏßÅ Íµ¨ÏÑ±
            var currentItem = ownedItem.itemData;

            equipItemButtons.Add(button);
            equipItemDatas.Add(currentItem);

            button.onClick.AddListener(() =>
            {
                // Ïù¥ÎØ∏ ÏÑ†ÌÉùÎêú Î≤ÑÌäºÏù¥Î©¥ Î¨¥Ïãú
                if (currentSelect == capturedButton)
                    return;

                // Í∏∞Ï°¥ ÏÑ†ÌÉùÎêú Î≤ÑÌäºÏù¥ ÏûàÏúºÎ©¥ Ïù¥ÎØ∏ÏßÄ Î≥µÏõê
                if (currentSelect != null)
                {
                    ResetItemButton();
                }

                Debug.Log($"Ïû•ÎπÑ ÏÑ†ÌÉùÎê®: {currentItem.name_item}");
                capturedImage.sprite = changedImage.selectedImage;
                currentSelect = capturedButton;
                OnEquipItemSelect?.Invoke(currentItem);
            });
        }
    }

    public void RefreshItemList()
    {
        equipItemButtons.Clear();
        equipItemDatas.Clear();

        foreach (Transform child in itemListPanel)
        {
            Destroy(child.gameObject);
        }

        if (toggleConsume.isOn)
        {
            var toggleEquipImage = toggleEquip.GetComponentInChildren<Image>();
            var toggleConsumeImage = toggleConsume.GetComponentInChildren<Image>();

            toggleConsumeImage.sprite = selectedImage;
            toggleEquipImage.sprite = unselectedImage;

            PrintConsumeItem();
        }
        else if (toggleEquip.isOn)
        {
            var toggleEquipImage = toggleEquip.GetComponentInChildren<Image>();
            var toggleConsumeImage = toggleConsume.GetComponentInChildren<Image>();

            toggleConsumeImage.sprite = unselectedImage;
            toggleEquipImage.sprite = selectedImage;

            PrintEquipItems();
        }
    }

    public void SetEquipItemButtonInteractableByJob(JobCategory category)
    {
        for (int i = 0; i < equipItemButtons.Count; i++)
        {
            if (equipItemButtons[i] == null) continue;
            
            bool canEquip = equipItemDatas[i].jobCategory == category;
            equipItemButtons[i].interactable = canEquip;
        }
    }

    public void SetAllEquipButtonsInteractable(bool state)
    {
        foreach (var btn in equipItemButtons)
        {
            if (btn != null)
                btn.interactable = state;
        }
    }

    public void ResetItemButton()
    {
        if (currentSelect == null) return;

        Image prevImage = currentSelect.GetComponent<Image>();
        prevImage.sprite = changedImage.defaultImage;
        currentSelect = null;
    }
}
